random_seeds: [42]

categories:
  - Digital_Music  # maps to data/Digital_Music.jsonl.gz

year_range: [2018, 2023]
max_reviews: 10000

temporal_split:
  train_years: [2018, 2019, 2020]
  val_year: 2021
  test_year: 2022

feature_set: hybrid  # options: structured, nlp, hybrid

models_to_run:
  ml:
    - random_forest
  dl: []

llm_models: []

output_dir: results/