# Configuration file for the Review Helpfulness Prediction Pipeline

# --- General Settings ---
random_seeds: [42, 123, 2025] # List of random seeds for ensuring reproducibility across runs. One run per seed.

# --- Data Source ---

# Set to a number (e.g., 1000000) to limit, or null/omit to load all.
max_initial_rows_per_category: 1000000 # Example: Load up to 1 million rows before any filtering

categories:
  # - CDs_and_Vinyl 
  - Books
  - Home_and_Kitchen
  - Beauty_and_Personal_Care
  # - Cell_Phones_and_Accessories

  # - Digital_Music #test category


year_range: [2010, 2019] # Inclusive range [start_year, end_year] to filter reviews by timestamp.

# --- Labeling Strategy ---
labeling:
  mode: "percentile" # 'threshold' or 'percentile'
  helpful_ratio_min: 0.75
  unhelpful_ratio_max: 0.25
  top_percentile: 0.10    # Used if mode: 'percentile'
  bottom_percentile: 0.10 # Used if mode: 'percentile'
  min_total_votes: 1      # Min votes for a review's product to be considered for labeling.
  min_helpful_votes: 1 
  use_length_filter: true
  min_review_words: 15
  max_review_words: 500 # Consider aligning with paper (e.g., 500)

# --- Temporal Data Splitting ---
temporal_split_years:
  train_years: [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017] #, 2018, 2019]
  val_year: 2018
  test_year: 2019

# --- Data Sampling Strategy ---
balanced_sampling:
  use_strict_balancing: true # Target 50/50 splits for ML/DL train/val/test
  samples_per_class:
    train: 5000
    val: 1250
    test: 1250
  max_total_samples_imbalanced: # Used if use_strict_balancing: false
    train: null
    val: null
    test: null

# --- Feature Engineering Settings ---
feature_set: hybrid       # 'structured', 'nlp', 'hybrid' (for ML/Hybrid DL)
text_max_features: 2000   # For TF-IDF

# --- Deep Learning Specific Settings ---
dl_feature_set: hybrid    # 'text', 'hybrid' (for DL input)
dl_num_structured_features: 5 # Expected count if dl_feature_set: 'hybrid'
dl_max_words: 10000
dl_max_len: 350
dl_embedding_dim: 64
dl_epochs: 10
dl_batch_size: 64


# --- Model Selection ---
models_to_run:
  ml: ['svm', 'random_forest'] # ['svm','random_forest','gradient_boosting'] # Available models ['svm','random_forest','gradient_boosting']
  dl: ['cnn','rcnn'] # ['cnn','rcnn'] # Available models ['cnn','rcnn'] 
  llm_openai: # Replace with your actual OpenAI model ID
    - "gpt-4o-mini" 
    #- 
  llm_google: # valid Gemini model ID
    # - "gemini-2.0-flash-lite" 
    #-

# --- LLM Evaluation Specific Configuration ---
llm_evaluation:
  openai_api_key_env_var: "OPENAI_API_KEY" # provider_api_key_env_var 
  google_api_key_env_var: "GOOGLE_API_KEY" # 
  # anthropic_api_key_env_var: "ANTHROPIC_API_KEY" # Example for future LLM implementations
  test_sample_size: null # null if running full prediction
  prompting_modes: ['zero_shot', 'few_shot']
  request_timeout: 30 # This will be passed to the wrapper's generate method
  max_retries: 5
  retry_delay: 5      # Initial delay (increases exponentially on retries)
  llm_max_output_tokens: 1

  # -- Zero-Shot Configuration --
  zero_shot_prompt_template: |
    Your task is to classify a customer review as either 'Helpful' or 'Unhelpful' based on its content.
    Use the following definitions to make your classification. Your response must be ONLY '1' (Helpful) or '0' (Unhelpful).
    Helpful (1): "The review provides specific details and elaborates on the product's features, performance, quality, or the user's direct experience with it. It often includes concrete examples, describes usage scenarios, or offers a reasoned perspective (e.g., pros and cons). The review is sufficiently informative, clearly written, and focuses primarily on the product itself, thereby aiding a potential buyer in making an informed decision. It offers insights beyond generic statements or the basic product description."
    Unhelpful (0): "The review is vague, lacks specific details or examples, or is excessively brief (e.g., few words lacking elaboration). It may consist of primarily emotional statements without supporting explanations tied to product experience. The content might focus predominantly on aspects external to the product's intrinsic qualities (e.g., issues *only* with shipping or seller, without evaluating the product itself), be difficult to understand due to significant issues with clarity or structure, or primarily pose a question rather than share an experience. It does not offer substantial, actionable information for a buyer's decision-making process regarding the product."

    Review Text:
    ---
    {review_text}
    ---

    Classification (1 or 0):

  # -- Few-Shot Configuration --
  few_shot:
    num_examples: 2 # Number of examples from training set.
    # Selection strategy from training data:
    # 'balanced_random', 'random', 'extreme_helpful_vote'
    example_selection_strategy: 'extreme_helpful_vote'

    # Format string for each selected example shown to the LLM (using 1/0).
    example_format: |
      "{review_text}" = {label_text}

    # Main prompt template for few-shot (using 1/0).
    prompt_template: |
      Your task is to classify a customer review as either 'Helpful' or 'Unhelpful' based on its content.
      Use the following definitions and illustrative examples to guide your classification of the final review. Your response for the final review must be ONLY '1' (Helpful) or '0' (Unhelpful).

      Definitions:
      Helpful (1): "The review provides specific details and elaborates on the product's features, performance, quality, or the user's direct experience with it. It often includes concrete examples, describes usage scenarios, or offers a reasoned perspective (e.g., pros and cons). The review is sufficiently informative, clearly written, and focuses primarily on the product itself, thereby aiding a potential buyer in making an informed decision. It offers insights beyond generic statements or the basic product description."
      Unhelpful (0): "The review is vague, lacks specific details or examples, or is excessively brief (e.g., few words lacking elaboration). It may consist of primarily emotional statements without supporting explanations tied to product experience. The content might focus predominantly on aspects external to the product's intrinsic qualities (e.g., issues *only* with shipping or seller, without evaluating the product itself), be difficult to understand due to significant issues with clarity or structure, or primarily pose a question rather than share an experience. It does not offer substantial, actionable information for a buyer's decision-making process regarding the product."

      Examples:
      ---
      {examples}
      ---

      Now classify this review:
      Review Text:
      ---
      {review_text}
      ---

      Classification (1 or 0):

# --- Output Directory ---
output_dir: results/ # Base directory for saving run results.