svm:
  C_pow: 0
  loss: hinge
  class_weight: null
  max_iter: 1000
random_forest:
  n_estimators: 300
  max_depth: 30
  min_samples_split: 4
  min_samples_leaf: 1
  class_weight: balanced_subsample
gradient_boosting:
  n_estimators: 150
  learning_rate_pow: -1
  max_depth: 2
  subsample: 0.8
cnn:
  embedding_dim: 256
  conv1d_filters: 256
  dense_units: 64
  dropout_cat: 0.3
  learning_rate_pow: -4
rcnn:
  embedding_dim: 64
  conv1d_filters: 256
  lstm_units: 128
  dense_units: 128
  dropout_cat: 0.4
  learning_rate_pow: -4
