
Library versions:
-------------------
- pandas: 2.2.3
- numpy: 1.26.4
- scikit-learn: 1.6.1
- matplotlib: 3.10.1
- tensorflow: 2.19.0
- openai: 1.74.0
- optuna: 4.3.0
- pyyaml: 6.0.2
- tqdm: 4.67.1
- textblob: 0.19.0
- joblib: 1.4.2
- weave: 0.51.42
- wandb: 0.19.9